/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lin
 */
public class AddGeneral extends javax.swing.JPanel {

    /**
     * Creates new form AddGeneral
     */
    public AddGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneGen = new javax.swing.JTabbedPane();
        panelOwnGen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOwnerAG = new javax.swing.JTable();
        panelPetGen = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePetAG = new javax.swing.JTable();
        panelVetGen = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableVetAG = new javax.swing.JTable();
        buttonAddGen = new javax.swing.JButton();
        buttonDelGen = new javax.swing.JButton();
        buttonBackGen = new javax.swing.JButton();

        tableOwnerAG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Last Name", "SSN", "BirthDate", "Birth Place"
            }
        ));
        jScrollPane1.setViewportView(tableOwnerAG);

        javax.swing.GroupLayout panelOwnGenLayout = new javax.swing.GroupLayout(panelOwnGen);
        panelOwnGen.setLayout(panelOwnGenLayout);
        panelOwnGenLayout.setHorizontalGroup(
            panelOwnGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOwnGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOwnGenLayout.setVerticalGroup(
            panelOwnGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOwnGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneGen.addTab("Owner", panelOwnGen);

        tablePetAG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Specie", "Age", "Weight"
            }
        ));
        tablePetAG.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablePetAG);

        javax.swing.GroupLayout panelPetGenLayout = new javax.swing.GroupLayout(panelPetGen);
        panelPetGen.setLayout(panelPetGenLayout);
        panelPetGenLayout.setHorizontalGroup(
            panelPetGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPetGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelPetGenLayout.setVerticalGroup(
            panelPetGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPetGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneGen.addTab("Pet", panelPetGen);

        tableVetAG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Last Name", "Salary", "Graduation"
            }
        ));
        tableVetAG.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tableVetAG);

        javax.swing.GroupLayout panelVetGenLayout = new javax.swing.GroupLayout(panelVetGen);
        panelVetGen.setLayout(panelVetGenLayout);
        panelVetGenLayout.setHorizontalGroup(
            panelVetGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVetGenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelVetGenLayout.setVerticalGroup(
            panelVetGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVetGenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        tabbedPaneGen.addTab("Vet", panelVetGen);

        buttonAddGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/add.png"))); // NOI18N
        buttonAddGen.setText("Add");
        buttonAddGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddGenActionPerformed(evt);
            }
        });

        buttonDelGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/delete.png"))); // NOI18N
        buttonDelGen.setText("Delete");
        buttonDelGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelGenActionPerformed(evt);
            }
        });

        buttonBackGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/back.png"))); // NOI18N
        buttonBackGen.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneGen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAddGen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDelGen))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonBackGen)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonBackGen)
                        .addGap(84, 84, 84)
                        .addComponent(buttonAddGen)
                        .addGap(49, 49, 49)
                        .addComponent(buttonDelGen)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tabbedPaneGen, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddGenActionPerformed
        int index = tabbedPaneGen.getSelectedIndex();
        
        switch(index){
            case 0: addOwner(); 
                break;
            case 1: addPet();
                break;
            case 2: addVet();
                break;
        
        }
    }//GEN-LAST:event_buttonAddGenActionPerformed

    private void buttonDelGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelGenActionPerformed
        int index = tabbedPaneGen.getSelectedIndex();
        
        switch(index){
            case 0: delOwner(); 
                break;
            case 1: delPet();
                break;
            case 2: delVet();
                break;
        
        }
    }//GEN-LAST:event_buttonDelGenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddGen;
    private javax.swing.JButton buttonBackGen;
    private javax.swing.JButton buttonDelGen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelOwnGen;
    private javax.swing.JPanel panelPetGen;
    private javax.swing.JPanel panelVetGen;
    private javax.swing.JTabbedPane tabbedPaneGen;
    private javax.swing.JTable tableOwnerAG;
    private javax.swing.JTable tablePetAG;
    private javax.swing.JTable tableVetAG;
    // End of variables declaration//GEN-END:variables

    private void addOwner() {
        ((DefaultTableModel)tableOwnerAG.getModel()).addRow(new Object []{});
    }

    private void addPet() {
        ((DefaultTableModel)tablePetAG.getModel()).addRow(new Object []{});
    }

    private void addVet() {
        ((DefaultTableModel)tableVetAG.getModel()).addRow(new Object []{});
    }

    private void delOwner() {
        int index = tableOwnerAG.getSelectedRow();
        
        if(index >= 0){
            ((DefaultTableModel)tableOwnerAG.getModel()).removeRow(index);
            
            if(tableOwnerAG.getRowCount() > 0){
                index = Math.min(index,tableOwnerAG.getRowCount() - 1);
                tableOwnerAG.getSelectionModel().setSelectionInterval(index, index);
            }
        }
    }

    private void delPet() {
        int index = tablePetAG.getSelectedRow();
        
        if(index >= 0){
            ((DefaultTableModel)tablePetAG.getModel()).removeRow(index);
            
            if(tablePetAG.getRowCount() > 0){
                index = Math.min(index,tablePetAG.getRowCount() - 1);
                tablePetAG.getSelectionModel().setSelectionInterval(index, index);
            }
        }
    }

    private void delVet() {
        int index = tableVetAG.getSelectedRow();
        
        if(index >= 0){
            ((DefaultTableModel)tableVetAG.getModel()).removeRow(index);
            
            if(tableVetAG.getRowCount() > 0){
                index = Math.min(index,tableVetAG.getRowCount() - 1);
                tableVetAG.getSelectionModel().setSelectionInterval(index, index);
            }
        }
    }
}
