/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

/**
 *
 * @author lin
 */
public class ResultPet extends javax.swing.JPanel {

    /**
     * Creates new form ResultPet
     */
    public ResultPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanePet = new javax.swing.JTabbedPane();
        panelInfoPet = new javax.swing.JPanel();
        labelAgePet = new javax.swing.JLabel();
        labelNamePet = new javax.swing.JLabel();
        textFieldNamePet = new javax.swing.JTextField();
        textFieldSpeciePet = new javax.swing.JTextField();
        labelSpeciePet = new javax.swing.JLabel();
        textFieldAgePet = new javax.swing.JTextField();
        textFieldWeightPet = new javax.swing.JTextField();
        labelWeightPet = new javax.swing.JLabel();
        panelPhotoPet = new javax.swing.JPanel();
        panelMedRecPet = new javax.swing.JPanel();
        scrollPaneVaccine = new javax.swing.JScrollPane();
        tableVaccine = new javax.swing.JTable();
        scrollPaneAppo = new javax.swing.JScrollPane();
        tableAppo = new javax.swing.JTable();
        buttonAddPet = new javax.swing.JButton();
        buttonDelPet = new javax.swing.JButton();
        buttonBackPet = new javax.swing.JButton();

        labelAgePet.setText("Age:");

        labelNamePet.setText("Name:");

        labelSpeciePet.setText("Specie:");

        labelWeightPet.setText("Weight:");

        javax.swing.GroupLayout panelPhotoPetLayout = new javax.swing.GroupLayout(panelPhotoPet);
        panelPhotoPet.setLayout(panelPhotoPetLayout);
        panelPhotoPetLayout.setHorizontalGroup(
            panelPhotoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        panelPhotoPetLayout.setVerticalGroup(
            panelPhotoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelInfoPetLayout = new javax.swing.GroupLayout(panelInfoPet);
        panelInfoPet.setLayout(panelInfoPetLayout);
        panelInfoPetLayout.setHorizontalGroup(
            panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPetLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoPetLayout.createSequentialGroup()
                        .addComponent(labelWeightPet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldWeightPet, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoPetLayout.createSequentialGroup()
                        .addComponent(labelAgePet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldAgePet, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoPetLayout.createSequentialGroup()
                        .addGroup(panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInfoPetLayout.createSequentialGroup()
                                .addComponent(labelNamePet)
                                .addGap(30, 30, 30)
                                .addComponent(textFieldNamePet, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInfoPetLayout.createSequentialGroup()
                                .addComponent(labelSpeciePet)
                                .addGap(25, 25, 25)
                                .addComponent(textFieldSpeciePet)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(panelPhotoPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panelInfoPetLayout.setVerticalGroup(
            panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPetLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPhotoPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoPetLayout.createSequentialGroup()
                        .addGroup(panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNamePet)
                            .addComponent(textFieldNamePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSpeciePet)
                            .addComponent(textFieldSpeciePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAgePet)
                            .addComponent(textFieldAgePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(panelInfoPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWeightPet)
                            .addComponent(textFieldWeightPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tabbedPanePet.addTab("Information", panelInfoPet);

        tableVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dosage"
            }
        ));
        tableVaccine.getTableHeader().setReorderingAllowed(false);
        scrollPaneVaccine.setViewportView(tableVaccine);

        tableAppo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Charge", "Notes", " Vet"
            }
        ));
        scrollPaneAppo.setViewportView(tableAppo);

        buttonAddPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/add.png"))); // NOI18N
        buttonAddPet.setText("Add");

        buttonDelPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/delete.png"))); // NOI18N
        buttonDelPet.setText("Delete");

        javax.swing.GroupLayout panelMedRecPetLayout = new javax.swing.GroupLayout(panelMedRecPet);
        panelMedRecPet.setLayout(panelMedRecPetLayout);
        panelMedRecPetLayout.setHorizontalGroup(
            panelMedRecPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedRecPetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedRecPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneVaccine, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(scrollPaneAppo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(panelMedRecPetLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(buttonAddPet, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(buttonDelPet, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMedRecPetLayout.setVerticalGroup(
            panelMedRecPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMedRecPetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneAppo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMedRecPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddPet)
                    .addComponent(buttonDelPet))
                .addGap(242, 242, 242))
        );

        tabbedPanePet.addTab("Medical Record", panelMedRecPet);

        buttonBackPet.setText("Back");
        buttonBackPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackPetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanePet, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBackPet)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBackPet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanePet, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackPetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddPet;
    private javax.swing.JButton buttonBackPet;
    private javax.swing.JButton buttonDelPet;
    private javax.swing.JLabel labelAgePet;
    private javax.swing.JLabel labelNamePet;
    private javax.swing.JLabel labelSpeciePet;
    private javax.swing.JLabel labelWeightPet;
    private javax.swing.JPanel panelInfoPet;
    private javax.swing.JPanel panelMedRecPet;
    private javax.swing.JPanel panelPhotoPet;
    private javax.swing.JScrollPane scrollPaneAppo;
    private javax.swing.JScrollPane scrollPaneVaccine;
    private javax.swing.JTabbedPane tabbedPanePet;
    private javax.swing.JTable tableAppo;
    private javax.swing.JTable tableVaccine;
    private javax.swing.JTextField textFieldAgePet;
    private javax.swing.JTextField textFieldNamePet;
    private javax.swing.JTextField textFieldSpeciePet;
    private javax.swing.JTextField textFieldWeightPet;
    // End of variables declaration//GEN-END:variables
}
