/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

/**
 *
 * @author lin
 */
public class ResultVet extends javax.swing.JPanel {

    /**
     * Creates new form ResultVet
     */
    public ResultVet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneVet = new javax.swing.JTabbedPane();
        panelInfoVet = new javax.swing.JPanel();
        labelNameVet = new javax.swing.JLabel();
        labelLastNameVet = new javax.swing.JLabel();
        labelSSNVet = new javax.swing.JLabel();
        labelBiDaVet = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        textFieldLastNameVet = new javax.swing.JTextField();
        textFieldSSNVet = new javax.swing.JTextField();
        textFieldBiDaVet = new javax.swing.JTextField();
        labelBiPlaVet = new javax.swing.JLabel();
        labelFocusVet = new javax.swing.JLabel();
        labelSpeVet = new javax.swing.JLabel();
        labelSalVet = new javax.swing.JLabel();
        labelGradVet = new javax.swing.JLabel();
        textFieldBiPlaVet = new javax.swing.JTextField();
        textFieldFocusVet = new javax.swing.JTextField();
        textFieldSpeVet = new javax.swing.JTextField();
        textFieldSalVet = new javax.swing.JTextField();
        textFieldGradVet = new javax.swing.JTextField();
        panelPetsVet = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonAddVet = new javax.swing.JButton();
        buttonDelVet = new javax.swing.JButton();
        buttonUpVet = new javax.swing.JButton();
        buttonDownVet = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        labelNameVet.setText("Name:");

        labelLastNameVet.setText("Last Name:");

        labelSSNVet.setText("SSN:");

        labelBiDaVet.setText("BirthDate:");

        textFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNameActionPerformed(evt);
            }
        });

        textFieldLastNameVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastNameVetActionPerformed(evt);
            }
        });

        textFieldBiDaVet.setMinimumSize(new java.awt.Dimension(97, 28));
        textFieldBiDaVet.setPreferredSize(new java.awt.Dimension(97, 28));

        labelBiPlaVet.setText("Birth Place:");

        labelFocusVet.setText("Focus:");

        labelSpeVet.setText("Speciality:");

        labelSalVet.setText("Salary:");

        labelGradVet.setText("Graduate At:");

        textFieldBiPlaVet.setMinimumSize(new java.awt.Dimension(97, 28));
        textFieldBiPlaVet.setPreferredSize(new java.awt.Dimension(97, 28));

        textFieldFocusVet.setMinimumSize(new java.awt.Dimension(97, 28));
        textFieldFocusVet.setPreferredSize(new java.awt.Dimension(97, 28));

        textFieldSpeVet.setMinimumSize(new java.awt.Dimension(97, 28));

        textFieldSalVet.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldSalVet.setPreferredSize(new java.awt.Dimension(97, 28));

        javax.swing.GroupLayout panelInfoVetLayout = new javax.swing.GroupLayout(panelInfoVet);
        panelInfoVet.setLayout(panelInfoVetLayout);
        panelInfoVetLayout.setHorizontalGroup(
            panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBiDaVet)
                    .addComponent(labelLastNameVet)
                    .addComponent(labelNameVet)
                    .addComponent(labelSSNVet)
                    .addComponent(labelSalVet)
                    .addComponent(labelFocusVet))
                .addGap(22, 22, 22)
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelInfoVetLayout.createSequentialGroup()
                        .addComponent(textFieldFocusVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSpeVet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldSpeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldLastNameVet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInfoVetLayout.createSequentialGroup()
                        .addComponent(textFieldSalVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelGradVet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldGradVet))
                    .addComponent(textFieldSSNVet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInfoVetLayout.createSequentialGroup()
                        .addComponent(textFieldBiDaVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBiPlaVet)
                        .addGap(20, 20, 20)
                        .addComponent(textFieldBiPlaVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        panelInfoVetLayout.setVerticalGroup(
            panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameVet)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLastNameVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastNameVet))
                .addGap(18, 18, 18)
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSSNVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSSNVet))
                .addGap(18, 18, 18)
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBiDaVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBiPlaVet)
                    .addComponent(textFieldBiPlaVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBiDaVet))
                .addGap(18, 18, 18)
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldSpeVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldFocusVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSpeVet)
                        .addComponent(labelFocusVet)))
                .addGap(18, 18, 18)
                .addGroup(panelInfoVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSalVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSalVet)
                    .addComponent(labelGradVet)
                    .addComponent(textFieldGradVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneVet.addTab("Information", panelInfoVet);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Specie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonAddVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/add.png"))); // NOI18N
        buttonAddVet.setText("Add");

        buttonDelVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/delete.png"))); // NOI18N
        buttonDelVet.setText("Delete");

        buttonUpVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/up.png"))); // NOI18N
        buttonUpVet.setText("Up");

        buttonDownVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/down.png"))); // NOI18N
        buttonDownVet.setText("Down");

        javax.swing.GroupLayout panelPetsVetLayout = new javax.swing.GroupLayout(panelPetsVet);
        panelPetsVet.setLayout(panelPetsVetLayout);
        panelPetsVetLayout.setHorizontalGroup(
            panelPetsVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPetsVetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panelPetsVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonDelVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAddVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonUpVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDownVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelPetsVetLayout.setVerticalGroup(
            panelPetsVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPetsVetLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelPetsVetLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(buttonAddVet)
                .addGap(18, 18, 18)
                .addComponent(buttonDelVet)
                .addGap(18, 18, 18)
                .addComponent(buttonUpVet)
                .addGap(18, 18, 18)
                .addComponent(buttonDownVet)
                .addContainerGap())
        );

        tabbedPaneVet.addTab("Pets", panelPetsVet);

        buttonBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneVet, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneVet, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNameActionPerformed

    private void textFieldLastNameVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastNameVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastNameVetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddVet;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDelVet;
    private javax.swing.JButton buttonDownVet;
    private javax.swing.JButton buttonUpVet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelBiDaVet;
    private javax.swing.JLabel labelBiPlaVet;
    private javax.swing.JLabel labelFocusVet;
    private javax.swing.JLabel labelGradVet;
    private javax.swing.JLabel labelLastNameVet;
    private javax.swing.JLabel labelNameVet;
    private javax.swing.JLabel labelSSNVet;
    private javax.swing.JLabel labelSalVet;
    private javax.swing.JLabel labelSpeVet;
    private javax.swing.JPanel panelInfoVet;
    private javax.swing.JPanel panelPetsVet;
    private javax.swing.JTabbedPane tabbedPaneVet;
    private javax.swing.JTextField textFieldBiDaVet;
    private javax.swing.JTextField textFieldBiPlaVet;
    private javax.swing.JTextField textFieldFocusVet;
    private javax.swing.JTextField textFieldGradVet;
    private javax.swing.JTextField textFieldLastNameVet;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldSSNVet;
    private javax.swing.JTextField textFieldSalVet;
    private javax.swing.JTextField textFieldSpeVet;
    // End of variables declaration//GEN-END:variables
}
